# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: openvino.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'openvino.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eopenvino.proto\x12\x08openvino\"1\n\nImageChunk\x12\x12\n\nchunk_data\x18\x01 \x01(\x0c\x12\x0f\n\x07is_last\x18\x02 \x01(\x08\"g\n\x0fPredictResponse\x12\x10\n\x08haserror\x18\x01 \x01(\x08\x12\x14\n\x0c\x65rrormessage\x18\x02 \x01(\t\x12\x10\n\x08\x64uration\x18\x03 \x01(\x01\x12\x1a\n\x12\x63itizenship_number\x18\x04 \x01(\t2O\n\x0fOpenvinoService\x12<\n\x07Predict\x12\x14.openvino.ImageChunk\x1a\x19.openvino.PredictResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openvino_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGECHUNK']._serialized_start=28
  _globals['_IMAGECHUNK']._serialized_end=77
  _globals['_PREDICTRESPONSE']._serialized_start=79
  _globals['_PREDICTRESPONSE']._serialized_end=182
  _globals['_OPENVINOSERVICE']._serialized_start=184
  _globals['_OPENVINOSERVICE']._serialized_end=263
# @@protoc_insertion_point(module_scope)
